import { Metadata } from "next";

import HeroSection from "@/components/HeroSection";
import SearchSection from "@/components/SearchSection";

export const metadata: Metadata = {
    title: "CryptoTracker",
    description: "Generated by create next app",
    icons: {
        icon: "/logo.svg"
    }
};

const HomePage = () => {
    return (
        <>
            <HeroSection />
            <SearchSection />
        </>
    )
};

export default HomePage;